name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:

env:
  IMAGE: ghcr.io/${{ github.repository }}/talentlink:latest

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t $IMAGE ./Team-TalentLink-DevOps/talentlink-main

      - name: Push image
        run: docker push $IMAGE

      - name: Upload pipeline diagram (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-diagram
          path: ./Team-TalentLink-DevOps/talentlink-main/diagrams/pipeline.mmd
