name: CI-CD

on:
  push:
    branches: [ main ]
  pull_request:

# Image will be pushed to GitHub Container Registry (GHCR)
env:
  IMAGE: ghcr.io/${{ github.repository }}/talentlink:latest

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write    # needed for GHCR
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: docker build -t $IMAGE ./talentlink-main

      - name: Push image
        run: docker push $IMAGE

      - name: Publish pipeline diagram (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-diagram
          path: ./talentlink-main/diagrams/pipeline.mmd

  # OPTIONAL deploy job (enable when you have a K8s cluster + kubeconfig)
  deploy:
    name: Deploy to Kubernetes
    needs: build-and-push
    runs-on: ubuntu-latest
    if: ${{ secrets.KUBE_CONFIG != '' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
      - name: Load kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
      - name: Apply manifests
        run: |
          kubectl apply -f ./talentlink-main/k8s/namespace.yaml
          kubectl apply -f ./talentlink-main/k8s/deployment.yaml
          kubectl apply -f ./talentlink-main/k8s/service.yaml
      - name: Wait for rollout
        run: kubectl -n pbl-devops rollout status deploy/talentlink
